#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 30 09:52:56 2021

@author: douglasbzzz
"""

import pandas as pd

df = pd.read_json(r'dados.json')
df.to_csv(r'dados.csv', index=None)